MOONSHOT-Team/MOONSHOT-SERVER

.github/workflows/CD.yml, .github/workflows/CI.yml, Dockerfile, build.gradle, deploy.sh, src/main/java/org/moonshot/server/global/config/SecurityConfig.java
- Resolved: #10
- CI.yml 작성
- CD.yml 작성
- deploy.sh 작성
- Spring actuator 추가 및 spring security endpoint 추가
=> [Feat] #10 - CI/CD 구축

src/main/java/org/moonshot/server/domain/keyResult/controller/KeyResultController.java, src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultCreateRequestDto.java, src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultCreateRequestInfoDto.java, src/main/java/org/moonshot/server/domain/keyResult/dto/request/KeyResultModifyRequestDto.java, src/main/java/org/moonshot/server/domain/keyResult/exception/KeyResultNotFoundException.java, src/main/java/org/moonshot/server/domain/keyResult/model/KeyResult.java, src/main/java/org/moonshot/server/domain/keyResult/repository/KeyResultRepository.java, src/main/java/org/moonshot/server/domain/keyResult/service/KeyResultService.java, src/main/java/org/moonshot/server/domain/objective/dto/request/KRCreateRequestDto.java, src/main/java/org/moonshot/server/domain/objective/dto/request/TaskCreateRequestDto.java, src/main/java/org/moonshot/server/global/common/exception/MoonshotControllerAdvice.java, src/main/java/org/moonshot/server/global/common/model/validator/TargetNumberValidator.java, src/main/java/org/moonshot/server/global/common/model/validator/ValidTargetNumber.java, src/main/java/org/moonshot/server/global/common/response/ErrorType.java, src/main/java/org/moonshot/server/global/common/response/SuccessType.java
- Resolved: #28 
- KeyResult의 내용을 수정하는 PATCH API 개발
- 해당 API로 변경 가능한 사항은 Title, startAt, expireAt(기간), target(목표치), KRState(상태)
- 해당 API에 순서변경을 넣지 않은 이유는 순서 변경에 처리되는 로직이 방대하고 해당 API가 적용되는 시점이 다르기 때문에 분리해도 된다고 판단하였음.
- DTO에 담겨있는 short idx나 int target 변수는 primitive type이기 때문에 null check가 불가능하여 Entity와 Dto에 들어가는 타입을 각각 Short, Integer와 같은 Wrapper type으로 변경하였음.
- target은 1000단위로 입력해야 되는 요구사항이 있어서 해당 사항을 체크하는 Custom Validator (@ValidTargetNumber) 어노테이션 및 Validator 구현하였음.
[(Spring Boot) Custom Validator 적용하는 방법, 단일 및 다중 필드](https://wildeveloperetrain.tistory.com/157)
=> [Feat] #28 - KeyResult PATCH API 개발

src/main/java/org/moonshot/server/domain/user/controller/UserController.java, src/main/java/org/moonshot/server/domain/user/dto/request/UserInfoRequest.java, src/main/java/org/moonshot/server/domain/user/dto/response/UserInfoResponse.java, src/main/java/org/moonshot/server/domain/user/model/User.java, src/main/java/org/moonshot/server/domain/user/service/UserService.java, src/main/java/org/moonshot/server/global/auth/filter/MoonshotExceptionHandler.java, src/main/java/org/moonshot/server/global/common/response/SuccessType.java
- Resolved: #37 
- 회원가입 후 닉네임 설정 API
- 프로필 수정 API
- User엔티티에서 닉네임은 중복 허용으로 변경했고, 카카오에서 이메일 받아오지 못하는 이슈로 email nullable 가능하게 해두었습니다!
- 앱잼에서는 회원가입 후 닉네임 설정 API 로만 사용될 예정입니다! 프로필 이미지 수정은 앱잼 이후에 구현 예정입니다!
- 닉네임 설정 시에는 requestBody에 nickname만 넣고, 프로필 설정 시에는 nickname, description만 넣으면 됩니다!
=> [Feat] #37 - 닉네임 설정, 프로필 수정 API 개발

src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java, src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java, src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java, src/main/java/org/moonshot/server/domain/keyresult/repository/KeyResultRepository.java, src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java, src/main/java/org/moonshot/server/domain/log/model/Log.java, src/main/java/org/moonshot/server/domain/objective/controller/IndexController.java, src/main/java/org/moonshot/server/domain/objective/dto/request/ModifyIndexRequestDto.java, src/main/java/org/moonshot/server/domain/objective/model/IndexService.java, src/main/java/org/moonshot/server/domain/objective/model/IndexTarget.java, src/main/java/org/moonshot/server/domain/objective/service/IndexTargetProvider.java, src/main/java/org/moonshot/server/domain/task/dto/request/TaskCreateRequestDto.java, src/main/java/org/moonshot/server/domain/task/dto/request/TaskSingleCreateRequestDto.java, src/main/java/org/moonshot/server/domain/task/exception/TaskNotFoundException.java, src/main/java/org/moonshot/server/domain/task/model/Task.java, src/main/java/org/moonshot/server/domain/task/repository/TaskRepository.java, src/main/java/org/moonshot/server/domain/task/service/TaskService.java, src/main/java/org/moonshot/server/global/common/model/validator/TargetNumberValidator.java, src/main/java/org/moonshot/server/global/common/response/ErrorType.java, src/main/java/org/moonshot/server/global/common/response/SuccessType.java
- Resolved: #42 
- Task, KeyResult 메인보드에서 위치를 수정하는 API 개발
- 기존 Task나 KeyResult의 위치를 변경하면 다른 엔티티의 데이터도 변경되어 최소 1개에서 최대 3개의 업데이트 쿼리가 발생하게 되는데 이런 쿼리를 한번에 bulk update로 구현하였음. (쿼리 1개로 축소)
- API Controller는 IndexController에 구현되어 있고, IndexController에서 IndexService의 구현체를 갈아끼우는 로직이 존재함. 각 구현체들은 KeyResult와 Task에 각각 구현되어 있음.
- JPQL이 파라미터를 기본적으로 int형으로 관리하기 때문에 Short와의 충돌이 발생하였음. 그래서 엔티티 Wrapper Type을 Integer로 변경하였음.
=> [Add] #42 - Task, KeyResult 순서 변경 API

src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java, src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
- Resolved: #46 
- Objective 삭제 API 구현
- Objective 삭제 후 KeyResultService의 deleteKeyResult(Objective objective); 메소드를 이용하여 deleteAllInBatch로 cascade 삭제를 대신함.
=> [Add] #46 - Objective 삭제 API

src/main/java/org/moonshot/server/domain/log/exception/InvalidRecordException.java, src/main/java/org/moonshot/server/domain/log/service/LogService.java, src/main/java/org/moonshot/server/global/auth/jwt/TokenResponse.java, src/main/java/org/moonshot/server/global/common/response/ErrorType.java, src/main/java/org/moonshot/server/global/constants/JWTConstants.java
- Resolved: #50 
- TokenResponse에 "Bearer" 추가하여 Response 수정하였습니다!
- 엑세스토큰 만료 시간을 2주로 변경하였습니다. 앱잼 이후 다시 변경하겠습니다!
- Log 생성 시 진척정도를  목표값보다 큰 값을 입력했을 경우 Exception 추가하였습니다!
- 없습니다!
=> [Fix] #50 - TokenResponse 수정 및 만료시간 변경 / Log 생성 관련 Exception 추가

src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java, src/main/java/org/moonshot/server/domain/log/exception/InvalidLogValueException.java, src/main/java/org/moonshot/server/domain/log/exception/InvalidRecordException.java, src/main/java/org/moonshot/server/domain/log/exception/LogNotFoundException.java, src/main/java/org/moonshot/server/domain/log/service/LogService.java, src/main/java/org/moonshot/server/global/common/response/ErrorType.java
- Resolved: #58 
- 엔티티 변경에 따른 keyResultService, LogService 수정했습니다.
- 기존 progress 계산을 keyResultService에서 진행하였는데 logService로 이동하였습니다.
- 기획 측 요구에 따라 이전값보다 큰 값을 입력 받았던 진척상황을 같은 상황일때만 예외가 발생하도록 수정하였습니다. (KR 수정 Log도 동일)
- Recordlog, UpdateLog가 생성되면 keyResult progress값 변경되도록 구현하였습니다.
없습니다!
=> [Fix] KeyResult 엔티티 변경에 따른 LogService, KeyResultService 변경

.gitignore, build.gradle, src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java, src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java, src/main/java/org/moonshot/server/domain/objective/dto/request/ObjectiveHistoryRequestDto.java, src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryKeyResultDto.java, src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryObjectiveListDto.java, src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryResponseDto.java, src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryTaskDto.java, src/main/java/org/moonshot/server/domain/objective/dto/response/ObjectiveGroupByYearDto.java, src/main/java/org/moonshot/server/domain/objective/model/Objective.java, src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepository.java, src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java, src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java, src/main/java/org/moonshot/server/global/common/response/SuccessType.java, src/main/java/org/moonshot/server/global/config/QuerydslConfig.java
- Resolved: #61 
- QueryDSL gradle 추가
- 히스토리 API 형식에 맞춘 DTO record 구현
- (페이징 적용 기준) 히스토리 조회 시 KeyResult 개수가 200개 미만으로 간주되어 BatchSize로 200으로 설정하였음
- 히스토리 조회 시 동적 쿼리 적용 (추후 Mybatis로 리팩토링 예정.. 지식이 부족하여 공부 후에 적용할 것임)
=> [Feat] #61 - 히스토리 조회 API 구현

src/main/java/org/moonshot/server/global/auth/filter/MoonshotExceptionHandler.java, src/main/java/org/moonshot/server/global/auth/security/JwtAuthenticationFilter.java, src/main/java/org/moonshot/server/global/config/SecurityConfig.java, src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java
- Resolved: #91 
- permitAll 대상 FilterChain에서 Token이 없어서 생기는 에러가 발생함. 그래서 이 에러를 발생시키지 않기 위해 토큰이 있는지 확인하는 로직 전에 다음 필터로 넘겨버리도록 하였음.
- WhiteList를 Constants로 분리하여 관리하도록 하였음.
=> [Fix] #91 - permitAll 대상 API token validation 회피 로직 추가

src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultApi.java, src/main/java/org/moonshot/server/domain/log/controller/LogApi.java, src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveApi.java, src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java, src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepository.java, src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java, src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java, src/main/java/org/moonshot/server/domain/task/controller/TaskApi.java, src/main/java/org/moonshot/server/domain/user/controller/UserApi.java
- Resolved: #107 
- Swagger 성공 케이스 ApiResponse schema 제외하여 response body 제대로 나오도록 설정
- modifyObjective response type 변경
- History 조회 동적 쿼리 API repository 로직 service layer로 변경
=> [Refactor] #107 - 히스토리 API 동적 쿼리 레포지토리 역할 줄이고 Service Layer에서 비즈니스 로직 처리로 변경

src/main/java/org/moonshot/server/domain/keyresult/dto/response/KeyResultResponseDto.java, src/main/java/org/moonshot/server/domain/keyresult/exception/KeyResultInvalidIndexException.java, src/main/java/org/moonshot/server/domain/keyresult/exception/KeyResultInvalidPositionException.java, src/main/java/org/moonshot/server/domain/keyresult/repository/KeyResultRepository.java, src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java, src/main/java/org/moonshot/server/domain/objective/controller/IndexApi.java, src/main/java/org/moonshot/server/domain/objective/controller/IndexController.java, src/main/java/org/moonshot/server/domain/objective/dto/request/ModifyIndexRequestDto.java, src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryObjectiveListDto.java, src/main/java/org/moonshot/server/domain/objective/exception/ObjectiveInvalidIndexException.java, src/main/java/org/moonshot/server/domain/objective/model/IndexTarget.java, src/main/java/org/moonshot/server/domain/objective/model/Objective.java, src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveJpaRepository.java, src/main/java/org/moonshot/server/domain/objective/service/IndexTargetProvider.java, src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java, src/main/java/org/moonshot/server/domain/task/exception/TaskInvalidIndexException.java, src/main/java/org/moonshot/server/domain/task/repository/TaskRepository.java, src/main/java/org/moonshot/server/domain/task/service/TaskService.java, src/main/java/org/moonshot/server/global/common/response/ErrorType.java
- Resolved: #110 
- Objective 생성 시 Idx가 0이 되고 존재하는 Objective Idx를 하나씩 밀기
- Objective Idx 변경 로직 추가
- KeyResult, Task Index Validation(0~2) 비즈니스 로직으로 이동 -> Objective는 사이즈가 10까지라서 하나의 인터페이스를 구현하려면 이동하는 게 맞다고 판단
- IndexController Swagger 설정
**Swagger 설정**
**Index의 위치가 정상적이지 않을 때(Objective, KeyResult, Task 모두 동일)**
**Index의 위치가 정상적일 때(성공)**
=> [Refactor] #110 - Index 수정 API Objective 추가 및 추가 예외 처리

src/main/java/org/moonshot/server/domain/keyresult/exception/KeyResultInvalidPeriodException.java, src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java, src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java, src/main/java/org/moonshot/server/global/common/response/ErrorType.java
- Resolved: #129 
- 히스토리 조회 NPE 해결
- OKR 데이터 생성 API KeyResult 기간 관련 예외처리
**예외 발생 시점**
```
if (dto.startAt().isBefore(objective.getPeriod().getStartAt()) ||
dto.expireAt().isAfter(objective.getPeriod().getExpireAt()) ||
dto.startAt().isAfter(dto.expireAt()))
```
1. Objective의 시작 날짜보다 KeyResult의 시작 날짜가 전일 때
2. Objective의 만료 날짜를 넘어서 KeyResult가 만료될 때
3. Objective의 만료 날짜를 넘어서 KeyResult가 시작할 때
4. KeyResult의 시작 날짜가 만료 날짜보다 이후일 때
=> [Fix] #129 - 히스토리 조회 NPE 해결 및 OKR 데이터 생성 API KeyResult 기간 관련 예외처리

src/main/java/org/moonshot/server/domain/user/service/UserService.java, src/main/java/org/moonshot/server/global/constants/JWTConstants.java
- Resolved: #187
- 카카오 회원가입 시 디스코드 알림 안오는 이슈 해결
- DiscordAppender에서 유저 이메일까지 넣어주고 있는데 카카오 회원가입의 경우 email값이 null이라 디스코드 알림에 실패하여서 해당 부분을 삼항연산자로 뺴서 email이 없는 경우 빈 문자열을 넣어주도록 수정하였습니다!
=> [Fix] #187 - 카카오 회원가입 시 디스코드 알림 안오는 이슈 해결

moonshot-api/src/main/java/org/moonshot/task/controller/TaskApi.java, moonshot-api/src/main/java/org/moonshot/task/controller/TaskController.java, moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java
- Resolved: #202 
- Task 관련 API 작업 진행하였습니다. 기존에 Task 추가 API가 있어서 삭제만 추가적으로 구현했고 수정API는 기획 측에 물어보고 작업 진행하겠습니다!
- 노션 API 명세서와 Swagger도 추가했습니다!
- API 테스트 결과는 다음과 같습니다!
=> [Feat] #202 - Task 삭제 API 구현

moonshot-api/src/main/java/org/moonshot/config/SchedulerConfig.java, moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java, moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java, moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java, moonshot-api/src/main/java/org/moonshot/user/service/UserDeleteScheduler.java, moonshot-api/src/main/java/org/moonshot/user/service/UserService.java, moonshot-api/src/main/resources/db/migration/V2__add_deleteAt_field.sql, moonshot-domain/src/main/java/org/moonshot/keyresult/repository/KeyResultRepository.java, moonshot-domain/src/main/java/org/moonshot/log/repository/LogRepository.java, moonshot-domain/src/main/java/org/moonshot/objective/repository/ObjectiveJpaRepository.java, moonshot-domain/src/main/java/org/moonshot/task/repository/TaskRepository.java, moonshot-domain/src/main/java/org/moonshot/user/model/SocialPlatform.java, moonshot-domain/src/main/java/org/moonshot/user/model/User.java, moonshot-domain/src/main/java/org/moonshot/user/repository/UserRepository.java
- Resolved: #214
-  회원탈퇴 SoftDelete 구현했습니다.
- 기존 존재했던 isDeleted 필드를 없애고 deleteAt 필드를 추가하였습니다. 회원탈퇴 후 Retention 기간 내 재가입시 deleteAt을 null로 바꾸어 주었습니다.
- 회원탈퇴 로직은 다음과 같습니다!
```
1. Scheduler를 통해 매일 새벽 2시에 삭제해야할 UserList를 전체 조회
2. UserList와 관련 ObjectiveList 조회 후 ObjectiveService로 넘김
3. Objective를 넘겨받은 ObjectiveService는 해당 Objective들과 관련된 KeyResultList 조회 후 KeyResultService로 요청 
4. KeyResultService는 해당 KeyResult들과 관련된 TaskList와 LogList  조회
5. 각 Service에서 List로 조회되어 있는 엔티티들 deleteAllInBatch 메소드로 삭제 진행
**  UserList에 User가 있는 경우에 2-5 단계 진행
```
- Flyway 통해서 DB Migration Test 진행 완료하였습니다. DB 변경할 때마다 baseline-version 변경 및 flyway-history 테이블이 존재하는 경우 `baseline-on-migrate: false` 로 지정해야한다고 합니다!
- taskService에서 해당 부분을 임시로 변경해두었습니다.. 다음 이슈에서 Validator 분리하여 작업 예정입니다!
- select 쿼리 5번, delete 쿼리 5번 날아가는데 더 줄일 …
=> [Feat] #214 - 회원탈퇴 SoftDelete 구현

moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java, moonshot-api/src/main/java/org/moonshot/keyresult/service/validator/KeyResultValidator.java, moonshot-api/src/main/java/org/moonshot/log/service/LogService.java, moonshot-api/src/main/java/org/moonshot/log/service/validator/LogValidator.java, moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java, moonshot-api/src/main/java/org/moonshot/objective/service/validator/ObjectiveValidator.java, moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java, moonshot-api/src/main/java/org/moonshot/task/service/validator/TaskValidator.java, moonshot-api/src/main/java/org/moonshot/user/service/UserService.java, moonshot-api/src/main/java/org/moonshot/user/service/validator/UserValidator.java, moonshot-api/src/main/java/org/moonshot/validator/IndexValidator.java
- Resolved: #231
- User, Log, Task Validator 분리하였습니다.
- index관련한 공통된 Validator는 IndexValidator로 따로 뺴두었습니다. 
- 기존 각 Validator에 있었던 유저관련 Validator는 UserValidator를 사용하도록 변경하였습니다!
- IndexValidator 패키징 위치가 괜찮은지 잘 모르겠네요..
- 누락된 부분이나 불필요하다고 생각되는 부분 있으면 리뷰 남겨주세요!
=> [Feat] #231 - User, Log, Task Validator 분리

build.gradle, moonshot-api/build.gradle, moonshot-api/src/main/java/org/moonshot/keyresult/controller/KeyResultApi.java, moonshot-api/src/main/java/org/moonshot/keyresult/controller/KeyResultController.java, moonshot-api/src/main/java/org/moonshot/log/controller/LogApi.java, moonshot-api/src/main/java/org/moonshot/log/controller/LogController.java, moonshot-api/src/main/java/org/moonshot/objective/controller/IndexApi.java, moonshot-api/src/main/java/org/moonshot/objective/controller/IndexController.java, moonshot-api/src/main/java/org/moonshot/objective/controller/ObjectiveApi.java, moonshot-api/src/main/java/org/moonshot/objective/controller/ObjectiveController.java, moonshot-api/src/main/java/org/moonshot/task/controller/TaskApi.java, moonshot-api/src/main/java/org/moonshot/task/controller/TaskController.java, moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java, moonshot-api/src/main/java/org/moonshot/user/controller/UserApi.java, moonshot-api/src/main/java/org/moonshot/user/controller/UserController.java, moonshot-api/src/main/java/org/moonshot/user/service/UserService.java, moonshot-auth/build.gradle, moonshot-auth/src/main/java/org/moonshot/jwt/JwtTokenProvider.java, moonshot-auth/src/main/java/org/moonshot/security/JwtAuthenticationFilter.java, moonshot-auth/src/main/java/org/moonshot/security/UserAuthentication.java, moonshot-auth/src/main/java/org/moonshot/security/service/UserPrincipalDetailsService.java, moonshot-common/src/main/java/org/moonshot/exception/user/UnauthorizedException.java, moonshot-domain/src/main/java/org/moonshot/user/model/LoginUser.java, moonshot-domain/src/main/java/org/moonshot/user/model/UserPrincipal.java, moonshot-domain/src/main/java/org/moonshot/user/repository/UserRepository.java
- Resolved: #236 
- @LoginUser라고 하는 현재 로그인한 유저의 아이디를 바인딩시켜주는 어노테이션을 개발하였습니다.
- 해당 개발 사항으로 인한 주요 변경사항은 다음과 같습니다.
- 1. SecurityContextHolder에 Custom하게 구현한 인증 객체를 SecurityContextHolder에 저장 후 나중에 API가 call 되었을 때 @AuthenticationPrincipal 어노테이션이 호출되었을 때 해당 인증 객체를 꺼내서 userId를 반환해주는 방식임(SpEL 사용)
- 참고로 AuthenticationPrincipal은 @LoginUser에 붙어 있음.
=> [Feat] 현재 로그인한 유저 어노테이션 구현

moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java, moonshot-api/src/main/java/org/moonshot/user/service/UserService.java, moonshot-external/src/main/java/org/moonshot/discord/DiscordAppender.java, moonshot-external/src/main/java/org/moonshot/discord/SignUpEvent.java, moonshot-external/src/main/java/org/moonshot/discord/SignUpEventListener.java
- Resolved: #238 
- UserService에서 DiscordAppender의 의존성이 직접적으로 사용되는 것을 고쳤습니다.
- 유저가 회원가입 시 DiscordAppender.signInAppend() 메소드를 직접 호출하는 방식을 제거하고 SignUpEvent를 만들었습니다.
흐름은 다음과 같습니다.
- UserService에서 ApplicationEventPublisher(ApplicationContext 가 구현해줘서 주입받아 그냥 사용하면 됨)를 주입받아 eventPublisher.publishEvent(new SignUpEvent()); 를 호출합니다.
- moonshot-external 모듈에 있는 discord 패키지에 SignUpEventListener를 만들고 해당 리스너에서 이벤트를 구독합니다.
- 해당 이벤트를 구독하고 의존성으로 주입되어 있는 DiscordAppender.signInAppend() 메소드를 호출합니다.
이로서 얻는 이점
- UserService와 DiscordAppender(알림 서비스) 와의 강한 결합도를 느슨하게 만들었습니다.
단점
- 로직의 흐름을 직접적으로 파악하기 어려울 수 있으니 코드리뷰하시고 이해가 안되는 부분은 리뷰 달아주세요!~~
=> [Refactor] #238 - Discord 회원가입 로직 이벤트 Pub-Sub 구조로 리팩토링

moonshot-api/src/main/java/org/moonshot/user/controller/UserApi.java, moonshot-api/src/main/java/org/moonshot/user/controller/UserController.java, moonshot-api/src/main/java/org/moonshot/user/service/UserService.java, moonshot-auth/src/main/java/org/moonshot/jwt/JwtTokenProvider.java, moonshot-auth/src/main/java/org/moonshot/jwt/JwtValidationType.java, moonshot-auth/src/main/java/org/moonshot/security/JwtAuthenticationFilter.java, moonshot-common/src/main/java/org/moonshot/constants/JWTConstants.java, moonshot-common/src/main/java/org/moonshot/exception/global/auth/InvalidRefreshTokenException.java, moonshot-common/src/main/java/org/moonshot/response/ErrorType.java
- Resolved: #240 
- 기존 엑세스토큰과 리프레쉬토큰이 같은 역할을 하고 있어 토큰 역할을 분리해주었습니다. 
- 구글로그인에서 /googleLogin으로 접속하면 서버 측에서 보내주는 방식이였는데 해당 부분을 카카오 로그인과 동일하게 클라이언트 측에서 처리하도록 변경하며 더 이상 사용되지 않는 /googleLogin을 없앴습니다~
=> [Refactor] #240 - 로그인 로직 리팩토링

moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java, moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java, moonshot-api/src/main/java/org/moonshot/task/service/TaskService.java, moonshot-domain/src/main/java/org/moonshot/objective/repository/ObjectiveJpaRepository.java
- Resolved: #248 
- Objective 삭제 시 Index 감소가 되지 않던 것 수정
- KeyResult, Task 생성, 삭제 시 Index 위치 조정 로직 변경
Objective, KeyResult, Task 생성 삭제 시 Index 수정하는 쿼리 최적화 수행하였습니다. 일례로 task만 보여드리도록 하겠습니다! 어차피 내부 DB SQL문은 똑같습니다 !!
[변경 전 쿼리 사진]
[변경 후 쿼리 사진]
=> [Fix] KeyResult, Task 생성, 삭제 시 Index 위치 조정 로직 변경

moonshot-api/src/main/java/org/moonshot/keyresult/service/KeyResultService.java, moonshot-api/src/main/java/org/moonshot/log/service/LogService.java, moonshot-api/src/test/java/org/moonshot/keyresult/service/KeyResultServiceTest.java, moonshot-api/src/test/java/org/moonshot/objective/service/ObjectiveServiceTest.java
- Resolved: #259 
KeyResultService 테스트 코드 작성을 하였습니다.
기존 ObjectiveService 테스트 코드와 다른 점은 given 절에 BDDMockito를 추가하여 좀 더 직관적인 테스팅 코드를 작성하였습니다.
테스트 코드에서 JPA에 의존하는 메소드 로직은 테스트 검증에서 뺐습니다. 또한 삭제하는 메소드도 JPA에 의존적이라고 판단하여 단위 테스트 코드에서는 뺐습니다. 추후 통합 테스트를 진행할 때 테스트를 진행하도록 하겠습니다!
테스트 로직이 KeyResultService를 무결하게 테스트하지 않는다고 생각하시는 경우에 어떤 부분을 보완하면 좋을지 알려주시면 감사하겠습니다~
=> [Feat] #259 - KeyResultService 테스트 코드 작성

moonshot-api/src/main/java/org/moonshot/objective/dto/response/HistoryResponseDto.java, moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java
- Resolved: #261 
O-KR 히스토리 조회 API 변경사항 반영
- 데이터 스펙이 변경됨에 따라 year를 stream에 처리하는 로직이 제거되어 어느정도 성능이 빨라졌는지 궁금해서 JMeter 테스트 결과를 아래에첨부하였습니다~ 동시에 쓰레드 100개가 100번 요청하는 상황으로 부하테스트를 진행하였습니다.
아래 테스트 결과를 보시면 기존 방식과 변경된 방식에서 평균 API latency는 비슷하지만 95% 99% 즉 가장 최악의 API 수행 시간은 기존 방식이 오래 걸림을 확인할 수 있었습니다. 아마 stream 처리 때문에 처리될 쓰레드가 쌓이면서 처리시간이 늘어나지 않았을까 추측해봅니다.
그리고 대규모 건당 처리량이 엄청 드라마틱하게 늘어난 것은 아니지만 꽤나 늘어난 것을 볼 수 있습니다.
[기존 API 구현 방법의 테스트]
[변경된 API 구현 방법의 테스트]
=> [Fix] #261 - O-KR 히스토리 조회 API 변경사항 반영

moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java, moonshot-auth/src/main/java/org/moonshot/config/CacheConfig.java, moonshot-auth/src/main/java/org/moonshot/config/RedisConfig.java, moonshot-auth/src/main/java/org/moonshot/security/service/UserPrincipalDetailsService.java, moonshot-domain/src/main/java/org/moonshot/user/repository/UserCustomRepository.java, moonshot-domain/src/main/java/org/moonshot/user/repository/UserCustomRepositoryImpl.java, moonshot-domain/src/main/java/org/moonshot/user/repository/UserJpaRepository.java, moonshot-domain/src/main/java/org/moonshot/user/repository/UserRepository.java
- Resolved: #263 
```
Hibernate: 
select
u1_0.user_id,
****
from
`user` u1_0 
where
u1_0.user_id=?
Hibernate: 
select
distinct o1_0.objective_id,
****
from
objective o1_0 
join
`user` u1_0 
on u1_0.user_id=o1_0.user_id 
where
u1_0.user_id=? 
and o1_0.is_closed=0 
order by
o1_0.idx
Hibernate: 
select
u1_0.user_id,
****
from
`user` u1_0 
where
u1_0.user_id=?
```
**별 표시는 쿼리문을 간략히 줄이기 위해 다 지우고 쓴 것임을 먼저 알려드리겠습니다 ! 참고해서 봐주세요~**
히스토리 조회 쿼리인데 user 정보를 항상 조회하는데에 오버헤드가 매우 크다고 생각했습니다. 또한 @LoginUser 어노테이션에 userId를 주입해줄 때 DB에서 유저의 정보를 조회해서 user의 id를 주입해주는데 항상 매 api 요청마다 DB에 다녀오는 것은 성능상 좋지 않다고 판단하였습니다. 또한 특정 API에서는 user 조회를 2번하는 경우도 존재하여 캐시를 적용하기로 결정하였습니다.
저희는 유저의 refresh token의 저장소를 redis에 저장하여 사용하고 있습니다. 또한 redis에 대한 **부하**가 그렇게 크지 않다고 판단했고 추가적인 저장소나 캐싱을 위한 **인프라 작업**이 필요없을 것 같아 Redis를 적용하기로 했습니다. 또한 …
=> [Refactor] #263 - User 데이터 캐싱

moonshot-api/src/main/java/org/moonshot/user/controller/UserController.java, moonshot-api/src/main/java/org/moonshot/user/service/UserService.java, moonshot-api/src/main/java/org/moonshot/user/service/social/GoogleLoginStrategy.java, moonshot-api/src/main/java/org/moonshot/user/service/social/KakaoLoginStrategy.java, moonshot-api/src/main/java/org/moonshot/user/service/social/SocialLoginContext.java, moonshot-api/src/main/java/org/moonshot/user/service/social/SocialLoginStrategy.java, moonshot-common/src/main/java/org/moonshot/constants/UserConstants.java, moonshot-common/src/main/java/org/moonshot/response/ErrorType.java, moonshot-domain/src/main/java/org/moonshot/user/model/User.java
- Resolved: #264 
유저 소셜 로그인에 전략 패턴을 적용하였습니다.
기존 UserService에서 로그인 로직을 수행하고 있었는데 UserService에 너무 과중한 책임이 부여되어 코드 길이가 굉장히 길었습니다. 이에 따라 코드 가독성이 낮아지고 의존성 주입된 객체들이 10개가 넘어가는 상황에서 분리가 필요하겠다고 생각하였습니다. 또한 switch case 분기를 통해 로직을 분리하던 것을 전략 패턴을 적용함으로써 SRP를 지키도록 만들어보았습니다.
API 테스트는 해보았고 입력에 지원되지 않는 소셜 플랫폼이 입력된다면 예외를 발생시키도록 하였습니다. 또한 바로 예외를 던지는 것이 아니라 SocialLoginContext의 support 메소드를 통해 가독성 있게 처리하도록 하였습니다.
또한 USER_RETENTION_PERIOD가 User 엔티티 최상단에 존재하는 부분이 이질적으로 느껴져 이를 UserConstants로 분리하여 적용하도록 하였습니다.
=> [Refactor] #264 - 유저 소셜 로그인 전략 패턴 적용

moonshot-api/src/main/java/org/moonshot/config/AsyncConfig.java, moonshot-api/src/main/java/org/moonshot/user/service/UserSignUpService.java, moonshot-api/src/main/java/org/moonshot/user/service/social/GoogleLoginStrategy.java, moonshot-api/src/main/java/org/moonshot/user/service/social/KakaoLoginStrategy.java, moonshot-api/src/main/java/org/moonshot/user/service/social/SocialLoginStrategy.java
- Resolved: #267 
유저 회원가입 이벤트 발행 로직을 비동기로 처리하도록 변경하였습니다.
비동기는 기본적으로 해당 요청의 반환 결과를 기다리지 않고 다음 실행을 이어나가는 방법을 말합니다. 로그인 특성상 회원가입 이벤트를 Discord에 로깅하는데 로깅하는 데까지 유저가 기다리는 시간이 많을 뿐더러, 이는 유저에게 불필요한 대기시간이므로 비동기로 분리하였습니다.
비동기로 분리했을 떄의 API 수행 시간 차이는 다음과 같이 테스트하였습니다.
- local 환경에서는 Discord 웹훅 연동이 되어 있지 않기 때문에 로깅을 하는데에 0.5초가 걸린다고 상정하고 Thread.sleep(500);을 통해 event 발행 메소드가 0.5초동안 수행되도록 하였습니다.
[기존 로직을 통해 이벤트를 발행한 경우]
[비동기로 변경된 로직으로 이벤트를 발행한 경우]
위 테스트 결과를 보시면 거의 이벤트의 I/O 시간만큼 유저의 회원가입 시간이 오래 걸린다는 것을 확인할 수 있습니다. 이를 통해 비동기 처리의 효과를 확인할 수 있습니다.
그리고 비동기 처리를 위한 쓰레드 풀을 설정하였는데요.
저희는 EC2 프리티어를 사용하고 있어서 싱글 코어입니다.
싱글 코어인데 쓰레드 풀의 크기를 크게 설정하면 정상적인 처리가 되지 않을 뿐더러, 회원가입 이벤트가 동시다발적으로 많이 발생하지 않을 것입니다. 그래서 쓰레드 풀의 크기를 4로 설정하고 keep-alive 시간도 60초로 설정하여 정상적으로 처리되도록 하였습니다.
또한, 대기 큐 오버플로우가 발생하면 이벤트를 받지 않고 폐기하도록 정책을 설정하였습니다.
잘못된 점 …
=> [Refactor] #267 - 유저 회원가입 이벤트 발행 비동기 처리

moonshot-api/src/main/java/org/moonshot/task/service/validator/TaskValidator.java, moonshot-api/src/test/java/org/moonshot/task/service/TaskServiceTest.java
- Resolved: #272 
BDDMocktio를 사용하여  Task생성과 관련된 테스트 코드를 작성하였습니다. 
우리 서비스의 경우 objective → keyResult → task 와 같이 의존성을 가지고 있으므로 테스트를 하기 위해서는 많은 세팅이 필요하기 때문에 mock 객체를 통해 테스트 하려는 코드가 의존하고 있는 객체를 가짜로 만들어 의존성 제거하고 객체의 동작을 통제할 수 있었습니다.
given절에는 기존 service 코드의 행위들을 mock객체에도 지정해주어야 하는데 몇몇 부분을 누락하여 진행하여 작성하는데 시간이 걸렸습니다. 
또한 생성을 검증할 때, 현재 mock객체를 사용하고 있기 때문에 직접적으로 task가 생성되었는지 검증할 방법이 없으므로, 다른 방법을 통해서 확인해야합니다.따라서 task관련해서는 bulkUpdateIdx를 이용해서 검증을 진행하였습니다.
테스트코드를 작성하면서 taskIdx에 -1을 넣으면 test에 성공하지 못하는 점을 발견하여 taskValidator를 수정하였습니다.
추가적으로 필요한 테스트코드가 있다면 알려주시면 작업하겠습니다 !
=> [Feat] #272 - TaskService 테스트 코드 작성

moonshot-api/src/test/java/org/moonshot/log/service/LogServiceTest.java
- Resolved: #274 
- LogService 내의 메서드에 대한 테스트 코드를 작성하였습니다.
<br>
- 진척 상황 입력 후 로그가 생성되는 경우 isKeyResult에 따른 반환값이 다른데, 하나의 메서드에서 처리할 수 있도록 `@ParameterizedTest`를 통해 구현하였습니다. 해당 테스트 결과는 다음과 같습니다.
- 이번에도 Stubbing을 하는 부분에서 시행착오가 있었습니다 .. 하하
- 추가적으로 필요한 테스트 코드가 있다면 알려주세요 !
https://velog.io/@ohzzi/junit5-parameterizedtest
=> [Feat] #274 - LogService 테스트 코드 작성

moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java, moonshot-common/src/main/java/org/moonshot/constants/RegexConstants.java, moonshot-domain/src/main/java/org/moonshot/objective/repository/ObjectiveCustomRepositoryImpl.java
- Resolved: #286 
1. 운영서버에서 유저가 초성으로만 닉네임을 입력하여 서버에러가 발생하였습니다.
수정 전 정규식은 일반 한글만 가능하도록 되어있었는데 자음 초성, 모음 초성도 가능하도록 정규식을 수정하였습니다. 해당 부분 클라 측에도 전달 예정입니다!
2. 소셜 API에서 다음과 같은 쿼리 에러가 발생하여서 해당 부분 수정하였습니다.
`Expression #3 of ORDER BY clause is not in SELECT list, references column 'moonshot.krl1_0.idx' which is not in SELECT list; this is incompatible with DISTINCT`
해당 에러는 DISTINCT를 사용할 때, ORDER BY절에 나열된 모든 컬럼들이 SELECT 리스트에 포함되어야 하는데 없어서 생긴 문제였습니다. 쿼리문에서 distinct를 제거하고 추후에 distinct를 해주는 방식으로 수정하였습니다. 순서를 보장해주기 위해서 LinkedHashSet을 사용하였습니다 !
=> [Fix] #286 - 소셜 쿼리 오류 수정 및 닉네임 정규표현식 수정

moonshot-api/src/main/resources/application.yml, moonshot-api/src/main/resources/db/migration/V4__DDL.sql, moonshot-domain/src/main/java/org/moonshot/user/model/User.java
- Resolved: #291 
구글 로그인 시 image_url 길이가 255보다 길어 에러가 발생하는 상황을 발견하였습니다.
그래서 길이를 512로 변경하는 작업을 수행하였습니다.
Flyway 수정을 위해 dev, prod 서버 application.yml 수정 작업 완료하도록 하겠습니다.
=> [Fix] 소셜 로그인 img_url 필드 MySQL 길이 대응

moonshot-api/src/main/java/org/moonshot/user/service/UserService.java, moonshot-auth/src/main/java/org/moonshot/jwt/JwtTokenProvider.java, moonshot-auth/src/main/java/org/moonshot/security/service/UserPrincipalDetailsService.java, moonshot-domain/src/main/java/org/moonshot/user/model/UserPrincipal.java
- Resolved: #294 
- Security 로그인 로직 중에서 UserDetails에 유저를 Redis에서 조회하여 주입하고 이를 커스텀 어노테이션에서 사용하는 로직이 존재하였습니다. 하지만 Access Token의 userId만을 주입하여 사용하여도 충분히 문제없는 로직이었습니다. 따라서 Redis에서 유저를 조회하여 UserDetails에 삽입하는 로직을 제거하고 JMeter로 성능 테스트를 진행하였습니다.
- JwtTokenProvider와 UserService에서 제대로 동작하지 않거나 불필요한 검증 로직 및 조회 로직을 삭제하였습니다.
- UserService에서 사용되는 `userService.findById` 를 `userService.findByIdWithCache`를 이용하여 Redis에 캐싱되어 있는 유저 정보를 사용하여 처리하도록 하였습니다.
`[JMeter 성능 테스트 - 기존 Redis 로직이었을 때 in Local]`
`[JMeter 성능 테스트 - Redis 조회 로직을 제거했을 때 in Local]`
로컬에서 테스트를 진행하였을 때 조회 API 10만 건에서 평균 13ms에서 11ms로 개선되었음을 확인하였습니다. 저희 서버 인프라 상 싱글 코어인만큼 성능 차이는 더 확연히 벌어질 것이라고 생각합니다.
모르는 부분이 있거나 이상한 점은 코드리뷰에 달아주세요 감사합니다 :)
=> [Refactor] #294 - Redis 유저 조회 로직 개선
