MOONSHOT-Team/MOONSHOT-SERVER

src/main/java/org/moonshot/server/global/auth/filter/MoonshotExceptionHandler.java
src/main/java/org/moonshot/server/global/config/SecurityConfig.java
src/main/resources/application-dev.yml
src/main/resources/application.yml

- Resolved: #5 
- 불필요한 파일 삭제
- Spring Security Config 설정
- MoonshotExceptionHandler 구성

[Feat] Spring Security 설정

---

src/main/java/org/moonshot/server/global/common/model/CustomLog.java
src/main/java/org/moonshot/server/global/common/model/Logging.java
src/main/java/org/moonshot/server/global/config/LoggerConfig.java

- Resolved: #3 
- 불필요한 파일 삭제
- AOP Custom Logger 구현
https://adjh54.tistory.com/133 - 참고해서 공부하셔도 좋을거 같습니다!

[Feat] #3 - AOP 로거 구현

---

src/main/java/org/moonshot/server/global/common/exception/MoonshotControllerAdvice.java
src/main/java/org/moonshot/server/global/common/exception/MoonshotException.java
src/main/java/org/moonshot/server/global/common/response/ApiResponse.java
src/main/java/org/moonshot/server/global/common/response/ErrorType.java
src/main/java/org/moonshot/server/global/common/response/SuccessType.java

- Resolved: #8 
CommonAPIResponse, CommonException 구현
- ApiResponse와 SuccessType, ErrorType 만들어주었습니다! 
솝커톤 때와 동일하게 SuccessType에서는 `HTTPmethod_어쩌구_SUCCESS` 이런 형식으로 하면 될 것 같아요! 
ex) `GET_CANDLE_SUCCESS`
- 일단 CommonException에 공통적으로 필요하다고 생각되는 것들만 넣어뒀는데 다른게 더 필요한게 있다면 말씀해주세요!

[Feat] #8 - CommonAPIResponse, CommonException 구현

---

README.md

- Resolved: #12 
- README.md 수정

[Docs] #12 - README.md 업데이트

---

src/main/java/org/moonshot/server/domain/Log/model/Log.java
src/main/java/org/moonshot/server/domain/Log/model/LogState.java
src/main/java/org/moonshot/server/domain/Task/model/Task.java
src/main/java/org/moonshot/server/domain/badge/model/Badge.java
src/main/java/org/moonshot/server/domain/heart/model/Heart.java
src/main/java/org/moonshot/server/domain/keyResult/model/KRState.java
src/main/java/org/moonshot/server/domain/keyResult/model/KeyResult.java
src/main/java/org/moonshot/server/domain/objective/model/Category.java
src/main/java/org/moonshot/server/domain/objective/model/Objective.java
src/main/java/org/moonshot/server/domain/user/model/SocialPlatform.java
src/main/java/org/moonshot/server/domain/user/model/User.java
src/main/java/org/moonshot/server/domain/userBadge/model/UserBadge.java
src/main/java/org/moonshot/server/global/common/model/Period.java
src/main/resources/application.yml

- Resolved: #14
- 3차 ERD 설계 회의한 내용으로 Entity 설계했습니다!
- 설계와 바뀐 부분은 다음과 같습니다!
1. profile_img 추가 
2. socialId Long -> String으로 변경 (google은 id가 길어서 변경했습니다!)
3. moonshotAccessToken 추가
- 기존 user만 있었던 패키지 구조를 도메인 패키지 구조로 세팅해두었습니다! 현재는 각 도메인별로 model만 만들어두었습니다!
- 연관관계 매핑 잘되었는지 확인해주세요!
- `@Column(nullable = false) `가 추가적으로 필요한 부분이 있는지 확인 부탁드립니다!
- KeyResult와 Objective에 startAt, expireAt이 공통적으로 사용되고 있어서 임베디드 타입으로 매핑해두었는데 괜찮을까요? Common-> model에 만들었는데 위치도 괜찮은지 ...
- 영속성전이, 고아객체 그 부분. 틀린 부분이 있다면 알려주세요!
- Enum 타입을 많이 만들었는데 변수명 마음에 안드는게 있다면 리뷰해주세요~ 추가적으로 metric은 기획 측에 물어보고 Enum으로 빼겠습니다.

[Feat] #14 - 초기 Entity 설계

---

src/main/java/org/moonshot/server/domain/keyResult/model/KeyResult.java
src/main/java/org/moonshot/server/domain/log/model/Log.java
src/main/java/org/moonshot/server/domain/log/model/LogState.java
src/main/java/org/moonshot/server/domain/task/model/Task.java

- Resolved: #20
- 아까 졸림 이슈로 대문자랑 소문자가 섞여있어서 해당 부분 소문자로 변경했습니다!

[Fix] #20 - 패키지명 소문자로 변경

---

README.md

- Resolved: #22 
- 아키텍쳐 수정
- ERD 수정
- 패키지 구조 수정
-  README.md 수정

[Docs] #22 - README.md 수정

---

build.gradle
src/main/java/org/moonshot/server/global/config/SecurityConfig.java
src/main/java/org/moonshot/server/global/config/SwaggerConfig.java
src/main/resources/application.yml

[Setting] #19 - Swagger 세팅

---

src/main/java/org/moonshot/server/domain/keyResult/repository/KeyResultRepository.java

[Fix] #30 - 코드 병합 에러 해결

---

src/main/java/org/moonshot/server/domain/keyResult/controller/KeyResultController.java
src/main/java/org/moonshot/server/domain/keyResult/service/KeyResultService.java
src/main/java/org/moonshot/server/global/config/SecurityConfig.java

- Resolved: #34 
- KeyResult 리스트로 Id를 받는게 아닌 단일 id를 받아 삭제

[Refactor] #34 - KeyResult 삭제 API 수정

---

src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
src/main/java/org/moonshot/server/domain/keyresult/dto/response/KRDetailResponseDto.java
src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
src/main/java/org/moonshot/server/domain/log/controller/LogController.java
src/main/java/org/moonshot/server/domain/log/dto/response/LogResponseDto.java
src/main/java/org/moonshot/server/domain/log/exception/InvalidLogValueException.java
src/main/java/org/moonshot/server/domain/log/model/Log.java
src/main/java/org/moonshot/server/domain/log/model/LogState.java
src/main/java/org/moonshot/server/domain/log/repository/LogRepository.java
src/main/java/org/moonshot/server/domain/log/service/LogService.java
src/main/java/org/moonshot/server/global/common/model/validator/LimitValueValidator.java
src/main/java/org/moonshot/server/global/common/model/validator/TargetNumberValidator.java
src/main/java/org/moonshot/server/global/common/model/validator/ValidLimitValue.java
src/main/java/org/moonshot/server/global/common/response/ErrorType.java
src/main/java/org/moonshot/server/global/common/response/SuccessType.java

- Resolved: #44
- KR 상세 조회 API 구현했습니다. 
- LogState의 Enum Value값 수정하였습니다.
- 로그 생성 시 prevNum 에 이전 로그값 들어가는 이슈해결했습니다. 
- 갓민철님의 도움으로 쿼리 갯수를 줄였습니다 !
- 진척 상황은 이전값보다 작지 않도록 
- 진척 상황은 목표값보다 작도록
해당 두개는 반영해두겠습니다!

[Feat] #44 - KR 상세 조회

---

src/main/java/org/moonshot/server/domain/user/controller/UserController.java
src/main/java/org/moonshot/server/domain/user/dto/request/UserInfoRequest.java
src/main/java/org/moonshot/server/domain/user/dto/response/UserInfoResponse.java
src/main/java/org/moonshot/server/domain/user/service/UserService.java
src/main/java/org/moonshot/server/global/common/response/SuccessType.java
src/main/java/org/moonshot/server/global/constants/RegexConstants.java

- Resolved: #56 
- 마이페이지 조회 API 구현했습니다.
- 프로필 수정 API 응답값 200 -> 204 NoContent로 변경했습니다.
- RegexConstant 생성하여 닉네임 정규식 추가했습니다.
- 닉네임, 한줄 소개 Validation 추가했습니다 !
없습니다 !

[Feat] #56 - 마이페이지 조회 API 구현 및 프로필 수정 Validation 추가

---

src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
src/main/java/org/moonshot/server/domain/log/controller/LogController.java
src/main/java/org/moonshot/server/domain/log/dto/response/AchieveResponseDto.java
src/main/java/org/moonshot/server/domain/log/service/LogService.java
src/main/java/org/moonshot/server/domain/objective/model/Objective.java
src/main/java/org/moonshot/server/global/common/response/SuccessType.java

- Resolved: #54 
- Objective Entity에 Progress 추가했습니다.  
- Krprogress가 70이상인 경우에 100%로 계산하여 이를 이용하여 O progress 를 계산하였습니다.
- Krprogress 계산로직과 동일하게 LogService 계산로직에 Oprogress 계산로직을 추가했습니다. 
```
(Id/ targert/ logNum / progress)
3개인 경우
KR1 : 52 / 2000 / 1700 / 85
KR2 : 53 / 200000 / 10000 / 50
KR3 : 54 / 200000 / 75
-> O progress 83%
2개인 경우
KR1 : 50 /  200000 / 150000 / 75
KR2 : 51 / 200000 / 10000 / 5
-> O progress 52%
1개인 경우
KR1 :  55 / 2000 / 1800 / 90%
->  O progress 100 % 
```
- O의 progress가 100%인 경우
-  O의 progress가 100%가 아닌 경우
- ERD 수정이 필요할 것 같습니다!!

[Chore] #54 -목표 달성 페이지를 위한 KR조회 Response 추가

---

src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java
src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java
src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultModifyRequestDto.java
src/main/java/org/moonshot/server/domain/keyresult/dto/response/KRDetailResponseDto.java
src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
src/main/java/org/moonshot/server/domain/log/dto/response/LogResponseDto.java
src/main/java/org/moonshot/server/domain/objective/dto/request/KRCreateRequestDto.java
src/main/java/org/moonshot/server/domain/objective/dto/request/ModifyObjectiveRequestDto.java
src/main/java/org/moonshot/server/domain/objective/dto/request/OKRCreateRequestDto.java
src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
src/main/java/org/moonshot/server/global/common/model/Period.java

- Resolved: #64 
- Objective, KeyResult 엔티티의 날짜 필드를 LocalDate로 변경
- 변경 후 관련된 DTO들의 타입도 모두 LocalDate로 변경

[Refactor] #64 - 클라이언트 날짜 타입 맞춰 데이터 처리

---

src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java

- Resolved: #69 
PR Merge import 문 빠진 문제 해결

[Hotfix] #69 : PR Merge import 문 빠진 문제 해결

---

src/main/java/org/moonshot/server/domain/objective/dto/response/DashboardResponseDto.java
src/main/java/org/moonshot/server/domain/objective/dto/response/ObjectiveResponseDto.java
src/main/java/org/moonshot/server/domain/objective/model/Objective.java

- Resolved: #68 
- 메인 대시보드 좌측 Objective List에 Progress Bar 수치 추가
- 메인 대시보드 좌측 Objective List 카테고리를 상세 데이터로 변경
- OKR Tree에 렌더링 되는 Objective 만료 여부 추가 (현재 날짜보다 이전의 expireAt의 데이터를 가지고 있고, 아직 isClosed가 false인 경우)
```
{
"status": 200,
"message": "O-KR 목록 조회에 성공하였습니다.",
"data": {
"objId": 2,
"objTitle": "통합 회원가입수 200,000건 돌파",
"objIsExpired": true,
"objListSize": 6,
"krList": [
{
"keyResultId": 4,
"keyResultTitle": "1번째 Key Result",
"taskList": [
{
"id": 10,
"title": "Acheck"
},
{
"id": 11,
"title": "Bcheck"
},
{
"id": 12,
"title": "Ccheck"
}
]
},
{
"keyResultId": 5,
"keyResultTitle": "2번째 Key Result",
"taskList": [
{
"id": 13,
"title": "Acheck"
},
{
"id": 14,
"title": "Bcheck"
},
{
"id": 15,
"title": "Ccheck"
}
]
}
],
"objList": [
{
"id": 7,
"title": "통합 회원가입수 200,000건 돌파",
"content": "제발 …
```

[Refactor] #68 - 메인 대시보드 Objective 조회 프로그레스바 수치 및 만료 여부 추가

---

src/main/java/org/moonshot/server/domain/keyresult/dto/response/KeyResultResponseDto.java
src/main/java/org/moonshot/server/domain/objective/dto/response/DashboardResponseDto.java
src/main/java/org/moonshot/server/domain/objective/dto/response/TreeResponseDto.java
src/main/java/org/moonshot/server/domain/task/dto/request/TaskCreateRequestDto.java
src/main/java/org/moonshot/server/domain/task/dto/response/TaskResponseDto.java
src/main/java/org/moonshot/server/domain/task/service/TaskService.java

- Resolved: #76 
- OKR 데이터 생성 시 task title이 비어있을 때 task의 정보를 DB에 저장하지 않음
- OKR 데이터 조회 시 tree 데이터를 objList와 분리함.
- OKR 데이터 조회 시 tree 데이터에 KeyResult와 Task의 idx를 포함하여 조회함.
```
{
"status": 200,
"message": "O-KR 목록 조회에 성공하였습니다.",
"data": {
"tree": {
"objId": 4,
"objTitle": "통합 회원가입수 200,000건 돌파",
"objIsExpired": false,
"objListSize": 4,
"krList": [
{
"keyResultId": 10,
"keyResultTitle": "1번째 Key Result",
"idx": 0,
"taskList": [
{
"id": 22,
"title": "Acheck",
"idx": 0
},
{
"id": 23,
"title": "Bcheck",
"idx": 1
},
{
"id": 24,
"title": "Ccheck",
"idx": 2
}
]
},
{
"keyResultId": 11,
"keyResultTitle": "2번째 Key Result",
"idx": 1,
"taskList": [
{
"id": 25,
"title": "Acheck",
"idx": 0
},
{
"id": 26,
"title": "Bcheck",
"idx": 1
},
{
"id": 27,
"title": "Ccheck",
"idx": 2
}
]
},
{
"keyResultId": 12, …
```

[Fix] #76 - OKR 트리 POST, GET API JSON 클라이언트 요청으로 변경

---

src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java
src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveJpaRepository.java
src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveRepository.java
src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java

- Resolved: #83 
ObjectiveRepository 인터페이스 구조 변경
- 기존 ObjectiveRepository -> ObjectiveJpaRepository
- ObjectiveCustomRepository 인터페이스와 이를 구현하는 ObjectiveCustomRepositoryImpl
- ObjectiveJpaRepository와 ObjectiveCustomRepository를 상속하는 ObjectiveRepository로 구현

[Refactor] #83 - ObjectiveRepository 인터페이스 구조 변경

---

src/main/java/org/moonshot/server/domain/badge/model/Badge.java
src/main/java/org/moonshot/server/domain/heart/model/Heart.java
src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java
src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
src/main/java/org/moonshot/server/domain/log/model/Log.java
src/main/java/org/moonshot/server/domain/objective/model/Objective.java
src/main/java/org/moonshot/server/domain/task/model/Task.java
src/main/java/org/moonshot/server/domain/task/service/TaskService.java
src/main/java/org/moonshot/server/domain/user/model/User.java
src/main/java/org/moonshot/server/domain/user/service/UserService.java
src/main/java/org/moonshot/server/domain/userBadge/model/UserBadge.java

- Resolved: #85 
- 엔티티 클래스 내에서 Builder를 사용하는데 id를 제외한 빌더를 위해 추가 처리하였음.
- Objective 삭제 시 Log 엔티티도 삭제되도록 하였음.
- CUD API가 많아서 서비스 클래스 위에 readOnly=true를 제거하고 읽기 API에 readOnly=true를 적용하였음.

[Refactor] #85 - 코드 피드백 반영

---

src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
src/main/java/org/moonshot/server/domain/log/controller/LogController.java
src/main/java/org/moonshot/server/domain/objective/controller/IndexController.java
src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
src/main/java/org/moonshot/server/domain/task/controller/TaskController.java
src/main/java/org/moonshot/server/domain/user/controller/ImageController.java
src/main/java/org/moonshot/server/domain/user/controller/UserController.java

- Resolved: #89
- 팟장님 피드백에 따라 ResponseEntity로 감싸도록 수정했습니다.
- 204 NoContent인 경우에 아무 내용이 뜨지 않도록 수정했습니다!

[Fix] #89 - ResponseEntity로 변경

---

src/main/java/org/moonshot/server/global/auth/security/JwtAuthenticationFilter.java
src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java

- Resolved: #93 
WhiteList 로그인 API 엔드포인트 추가 및 Token Authentication 회피 로직 변경

[Fix] #93 - WhiteList 로그인 API 엔드포인트 추가 및 Token Authentication 회피 로직 변경

---

src/main/java/org/moonshot/server/global/constants/JWTConstants.java

- Resolved: #95 
클라 요청으로 인한 엑세스토큰 시간 1분으로 변경

[Fix] #95 - 엑세스토큰 시간 1분으로 변경

---

src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultApi.java
src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveApi.java
src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
src/main/java/org/moonshot/server/global/config/SwaggerConfig.java
src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java

- Resolved: #99 
- Objective, KeyResult Swagger 설명 인터페이스 구현
- 스웨거 JWT token 입력 설정 SwaggerConfig에서 수정
- 스웨거 관련 엔드포인트 화이트리스트 수정 (filter level)

[Feat] #99 - Objective, KeyResult Swagger 적용

---

src/main/java/org/moonshot/server/domain/log/controller/LogApi.java
src/main/java/org/moonshot/server/domain/log/controller/LogController.java
src/main/java/org/moonshot/server/domain/task/controller/TaskApi.java
src/main/java/org/moonshot/server/domain/task/controller/TaskController.java
src/main/java/org/moonshot/server/domain/user/controller/UserApi.java

- Resolved: #98 
- Log, Task Swagger 적용했습니다. 
- User Swagger 수정

[Feat] #98 - Log, Task Swagger 적용 및 User Swagger 수정

---

src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java
src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java
src/main/java/org/moonshot/server/domain/keyresult/dto/response/KRDetailResponseDto.java
src/main/java/org/moonshot/server/domain/keyresult/model/KeyResult.java
src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
src/main/java/org/moonshot/server/domain/log/service/LogService.java
src/main/java/org/moonshot/server/domain/objective/model/Objective.java

- Resolved: #104 
- KeyResult의 descriptionBefore, descriptionAfter 삭제 후 관련 변경 사항 모두 수정
- Objective의 boolean 값 MySQL 타입 bit로 저장되는거 TINYINT(1)로 수정

[Refactor] #104 - KeyResult Description 요구사항 변경으로 엔티티 수정 및 로직 변경

---

README.md
src/main/java/org/moonshot/server/domain/objective/exception/DateInputRequiredException.java
src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
src/main/java/org/moonshot/server/global/auth/jwt/JwtTokenProvider.java
src/main/java/org/moonshot/server/global/auth/security/JwtExceptionFilter.java
src/main/java/org/moonshot/server/global/common/response/ErrorType.java

- Resolved: #106 
- signatureException 예외처리
- 기간연장 및 목표완료 API isClosed = false일때 expireAt 없으면 예외처리
- 리드미 ERD 및 프로필 업데이트
없습니다!

[Fix] #106 - 예외 처리 추가 및 리드미 수정

---

src/main/java/org/moonshot/server/domain/objective/exception/UserObjectiveEmptyException.java
src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
src/main/java/org/moonshot/server/global/common/response/ErrorType.java

- Resolved: #113 
OKR 데이터 존재하지 않을 때 Objective 조회 시 예외 처리

[Fix] #113 - OKR 데이터 존재하지 않을 때 Objective 조회 시 예외 처리

---

src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestDto.java
src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultCreateRequestInfoDto.java
src/main/java/org/moonshot/server/domain/keyresult/dto/request/KeyResultModifyRequestDto.java
src/main/java/org/moonshot/server/domain/log/dto/request/LogCreateRequestDto.java
src/main/java/org/moonshot/server/domain/objective/dto/request/KRCreateRequestDto.java

- Resolved: #112 
- KR 목표값, Log 진척상황 값 Max Validation 변경
- Validation message 추가
없습니다!

[Fix] #112 - KR 목표값, Log 진척상황 값 Max Validation 변경

---

src/main/java/org/moonshot/server/global/config/SwaggerConfig.java

- Resolved: #117 
Swagger generated Server https 설정
Swagger generated Server https 설정

[Fix] #117 - Swagger generated Server https 설정

---

src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java

[Fix] #119 - Security Config Swagger URI 추가

---

src/main/java/org/moonshot/server/global/config/SecurityConfig.java
src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java

- Resolved: #119 
Security Filter Swagger URI ignoring
Security Filter Swagger URI ignoring

[Fix] #119 - Security Filter Swagger URI ignoring

---

src/main/java/org/moonshot/server/global/config/SecurityConfig.java

- Resolved: #119 
Security Filter Swagger URI ignoring Bean 등록
Security Filter Swagger URI ignoring Bean 등록

[Hotfix] #119 - Security Filter Swagger URI ignoring Bean 등록

---

src/main/java/org/moonshot/server/global/config/SecurityConfig.java

- Resolved: #125 
- CORS 서버 URL 추가

[Fix] #125 - CORS 서버 URL 추가

---

src/main/java/org/moonshot/server/global/common/exception/MoonshotControllerAdvice.java
src/main/java/org/moonshot/server/global/config/SecurityConfig.java
src/main/java/org/moonshot/server/global/constants/WhiteListConstants.java

- Resolved: #127 
- Moonshot Exception Discord 알림 제외
- SecurityConfig 필요 없는 설정 제거

[Fix] #127 - Moonshot Exception Discord 알림 제외, Security Config 재설정

---

src/main/java/org/moonshot/server/domain/user/service/UserService.java
src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java

- Resolved: #116
회원가입 시 Discord 알림 추가
되길 바라며 ..

[Feat] #116 - 회원가입 시 Discord 알림 추가

---

src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java

- Resolved: #139 
1. KeyResult 및 Task 인덱스가 정상 위치에 있는지 검증 예외 처리
2. 메소드 분리 작업 진행
**KeyResult가 정상적인 위치에 있지 않을 때**
**Task가 정상적인 위치에 있지 않을 때**

[Fix] #139 - KeyResult 및 Task 인덱스가 정상 위치에 있는지 예외 처리 및 메소드 분리 작업 진행

---

README.md

- Resolved: #142
- API 명세서 링크 삭제
- Tech Stack 에 Querydsl 추가

[Docs] #142 -  README.md 수정

---

src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveApi.java

- Resolved: #147 
Objecitve 삭제 API Swagger 설정 변경

[Fix] #147 - Objective 삭제 API Swagger 설정 변경

---

src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
src/main/java/org/moonshot/server/domain/log/dto/request/LogCreateRequestDto.java

- Resolved: #145 
- 기존 상태 변경 시 추가한 Exception으로 인하여 안되는 이슈가 있어 KR 상태 변경만 가능하도록 수정하였습니다.

[Fix] #145 - KR 상태 변경만 가능하도록 수정

---

src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryKeyResultDto.java

- Resolved: #150
- History KR title Response 수정

[Fix] #150 - History KR title Response 수정

---

src/main/java/org/moonshot/server/domain/objective/dto/response/DashboardResponseDto.java
src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java

- Resolved: #152
OKR 리스트 조회 시 닉네임 Response 추가

[Fix] #152 - OKR 리스트 조회 시 닉네임 Response 추가

---

src/main/java/org/moonshot/server/domain/keyresult/dto/response/KRDetailResponseDto.java
src/main/java/org/moonshot/server/domain/keyresult/dto/response/KeyResultResponseDto.java
src/main/java/org/moonshot/server/domain/log/service/LogService.java

- Resolved: #155 
DTO String 내용 수정

[Fix] #155 - DTO String 내용 수정

---

src/main/java/org/moonshot/server/global/config/SwaggerConfig.java

- Resolved: #157 
도메인 변경으로 인한 코드 수정
도메인 변경으로 인한 코드 수정

[Fix] #157 - 도메인 변경으로 인한 코드 수정

---

src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryObjectiveListDto.java

- Resolved: #159 
히스토리 날짜 String 포맷팅 변경

[Fix] History 날짜 String 포맷팅 변경

---

src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java

- Resolved: #162 
OKR 데이터 생성 API KR List에서 NPE 발생 처리

[Fix] #162 - OKR 데이터 생성 API KR List에서 NPE 발생 처리

---

src/main/java/org/moonshot/server/domain/user/service/UserService.java
src/main/java/org/moonshot/server/global/common/util/ApiCallUtil.java
src/main/java/org/moonshot/server/global/constants/DiscordConstants.java
src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java
src/main/java/org/moonshot/server/global/external/discord/DiscordWebHook.java
src/main/resources/application-dev.yml

- Resolved: #154
- 회원가입 시 디스코드 알림오도록 추가헸습니다.

[Feat] #154 - 회원가입 디스코드 알림 추가

---

src/main/java/org/moonshot/server/domain/objective/dto/response/HistoryResponseDto.java
src/main/java/org/moonshot/server/domain/objective/dto/response/YearDto.java

- Resolved: #164 
- 히스토리 조회 API 연도 데이터 리스트 내 객체 DTO로 변경

[Fix] #164 - History 조회 API years List로 변경

---

src/main/java/org/moonshot/server/domain/user/service/UserService.java
src/main/java/org/moonshot/server/global/constants/DiscordConstants.java
src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java

- Resolved: #166
- 알림에 사용자 프로필 이미지 썸네일로 추가
- 회원가입 중 디스코드 알림 실패시 회원가입까지 안되는 경우를 대비하기 위해 Transactional Propagation 분리

[Refactor] #166 - 회원가입 디스코드 알림 리팩토링

---

src/main/java/org/moonshot/server/domain/user/service/UserService.java

- Resolved: #168 
- 회원가입 알림 안오는 이슈 해결
- try-catch 문 추가하였음.

[Fix] #168 - 회원가입 알림 안오는 이슈 해결

---

src/main/java/org/moonshot/server/domain/user/service/UserService.java
src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java

- Resolved: #168 
- 이미지 썸네일 삭제
- 이거 떄문인지는 모르겠지만 ..일단 해볼게요

[Del] #168 - 디스코드 알림 이미지 썸네일 삭제

---

src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java

- Resolved: #173 
히스토리 조회 달성률 조건 정렬 버그 픽스

[Fix] 히스토리 조회 달성률 조건 정렬 버그 픽스

---

src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java

- Resolved: #175
KR 기간 수정이 가능해짐에 따라 코드를 수정하였습니다.
KR 기간 수정 가능하도록 코드 수정

[Fix] #175 -  KR 기간 수정 가능하도록 코드 수정

---

.github/workflows/CI.yml
src/main/resources/application-dev.yml
src/main/resources/application.yml

- Resolved: #177 
- 더미 데이터 주입을 위한 CI.yml 수정

[Fix] #177 - 더미 데이터 주입을 위한 CI.yml 수정

---

.github/workflows/CD.yml

- Resolved: #179 
더미 데이터 주입을 위한 CD.yml 수정

[Fix] #179 - 더미 데이터 주입을 위한 CD.yml 수정

---

src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java

- Resolved: #181 
KR 수정시 달성률 오류 수정
KR 수정시 달성률 오류 수정

[Fix] #181 - KR 수정시 달성률 오류 수정

---

src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveJpaRepository.java
src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java

- Resolved: #183 
- 대시보드 데이터 조회 API 버그 수정
- Objective fetch join @Query 내의 문장 where 절 조건 잘못된거 제거
- findAllByUserId User fetch join 추가

[Fix] #183 - 대시보드 데이터 조회 API 버그 수정

---

src/main/java/org/moonshot/server/domain/objective/repository/ObjectiveCustomRepositoryImpl.java

- Resolved: #185 
히스토리 기본 정렬 최신순으로 안되는 버그 수정

[Fix] #185 - 히스토리 기본 정렬 최신순으로 안되는 버그 수정

---

src/main/java/org/moonshot/server/domain/user/service/UserService.java
src/main/java/org/moonshot/server/global/constants/JWTConstants.java
src/main/java/org/moonshot/server/global/external/discord/DiscordAppender.java

- Resolved: #189 
- 엑세스 토큰 만료기간 2주로 변경 
- 회원가입 디스코드 알림 시 사용자 프로필 이미지도 받아오도록 수정
- 갓 언 석 짱 !

[Fix] #189 - 엑세스 토큰 만료기간 2주로 변경 

---

src/main/java/org/moonshot/server/domain/keyresult/controller/KeyResultController.java
src/main/java/org/moonshot/server/domain/keyresult/service/KeyResultService.java
src/main/java/org/moonshot/server/domain/log/controller/LogController.java
src/main/java/org/moonshot/server/domain/log/service/LogService.java
src/main/java/org/moonshot/server/domain/objective/controller/IndexController.java
src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveApi.java
src/main/java/org/moonshot/server/domain/objective/controller/ObjectiveController.java
src/main/java/org/moonshot/server/domain/objective/service/IndexTargetProvider.java
src/main/java/org/moonshot/server/domain/objective/service/ObjectiveService.java
src/main/java/org/moonshot/server/domain/task/controller/TaskController.java
src/main/java/org/moonshot/server/domain/task/service/TaskService.java
src/main/java/org/moonshot/server/domain/user/controller/ImageController.java
src/main/java/org/moonshot/server/domain/user/controller/UserController.java
src/main/java/org/moonshot/server/domain/user/service/UserService.java

- Resolved: #191 
- 불변 메소드 파라미터 final 키워드 붙이기
- 사용하지 않는 import 문 삭제
- UserService switch case 변경
final 붙이고 API 테스트 모두 진행 후 정상 작동 확인하였습니다!

[Refactor] #191 - 불변 변수 final 키워드 붙이기

---

Dockerfile

- Resolved: #195 
Dockerfile 빌드 파일 위치 수정

[Fix] #195 - Dockerfile build 파일 위치 수정

---

.gitignore
build.gradle
moonshot-api/src/main/java/org/moonshot/objective/dto/request/ModifyObjectiveRequestDto.java
moonshot-api/src/main/java/org/moonshot/objective/dto/request/OKRCreateRequestDto.java
moonshot-api/src/main/java/org/moonshot/objective/dto/response/HistoryResponseDto.java
moonshot-api/src/main/java/org/moonshot/objective/service/ObjectiveService.java
moonshot-api/src/main/resources/application-dev.yml
moonshot-api/src/main/resources/application.yml
moonshot-api/src/test/java/org/moonshot/objective/service/ObjectiveServiceTest.java
moonshot-domain/src/main/java/org/moonshot/objective/dto/request/ModifyIndexRequestDto.java
moonshot-domain/src/main/java/org/moonshot/user/model/User.java

- Resolved: #199
- Resolved: #200 
Mockito를 이용해서 ObjecitveService 테스트코드를 작성했습니다.
테스트 코드 짜면서 Dto Mock 객체를 생성할 일이 있어서 Dto에 Lombok builder 어노테이션을 적용하여 생성할 수 있도록 하였습니다.

[Feat] #200 - ObjectiveService 테스트 코드 작성 및 OSIV 설정 변경

---

moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
moonshot-api/src/main/resources/application.yml
moonshot-common/src/main/java/org/moonshot/filter/MDCFilter.java
moonshot-common/src/main/java/org/moonshot/util/HttpRequestUtil.java
moonshot-common/src/main/java/org/moonshot/util/MDCUtil.java

- Resolved: #208 
카카오 로그인 Origin에 따라 RedirectUri 변경하도록 수정

[Fix] #208 - 카카오 로그인 Origin에 따라 RedirectUri 변경하도록 수정

---

moonshot-api/src/main/java/org/moonshot/user/service/UserService.java

- Resolved: #208 
- 카카오 로그인 URL 체크 로깅

[Hotfix] #208 - 카카오 로그인 URL 체크 로깅

---

moonshot-api/src/main/java/org/moonshot/user/service/UserService.java

- Resolved: #208 
카카오 로그인 URL 체크 로깅 삭제

[Del] #208 - 카카오 로그인 URL 체크 로깅 삭제

---

moonshot-api/src/main/java/org/moonshot/keyresult/controller/KeyResultController.java
moonshot-api/src/main/java/org/moonshot/log/controller/LogController.java
moonshot-api/src/main/java/org/moonshot/objective/controller/ObjectiveController.java
moonshot-api/src/main/java/org/moonshot/task/controller/TaskController.java
moonshot-api/src/main/java/org/moonshot/user/controller/UserController.java
moonshot-api/src/main/resources/application.yml

- Resolved: #215 
- API AOP Logger 추가했습니다.
- 기존의 Spring Security Logging을 제거했습니다.

[Feat] #215 - Api AOP Logger 추가

---

.github/workflows/dev-CD.yml
.github/workflows/dev-CI.yml
.github/workflows/prod-CD.yml
.github/workflows/prod-CI.yml
Dockerfile
moonshot-api/src/main/resources/logback-prod.xml

- Resolved: #220 
CI, CD job name 변경

[Fix] #220 - CI, CD job name 변경

---

.github/workflows/dev-CD.yml
.github/workflows/dev-CI.yml
.github/workflows/prod-CD.yml
.github/workflows/prod-CI.yml

- Resolved: #223 
prod-CD.yml 버그 수정
prod-CD.yml 버그 수정

[Fix] #223 - prod-CD.yml 버그 수정

---

.github/workflows/prod-CD.yml
.github/workflows/prod-CI.yml

- Resolved: #223 
prod CI, CD.yml 버그 수정

[Fix] #223 - prod CI, CD.yml 버그 수정

---

moonshot-api/src/main/java/org/moonshot/log/service/LogService.java

- Resolved: #233
Log 이전 로그값이 0으로 뜨는 버그 해결했습니다~!

[Fix] #233 - Log 이전 로그값이 0으로 뜨는 버그 해결

---

moonshot-domain/src/main/java/org/moonshot/objective/model/Criteria.java

- Resolved: #250 
Criteria 조건 워딩 변경
Criteria 조건 워딩 변경

[Fix] #250 - Criteria 조건 워딩 변경

---

build.gradle
moonshot-api/src/main/resources/application.yml
moonshot-api/src/main/resources/logback-prod.xml
moonshot-api/src/main/resources/sentry-appender.xml

- Resolved: #269 
Sentry 로깅 기능 추가

[Feat] #269 - Sentry 로깅 기능 추가

---

moonshot-api/src/main/java/org/moonshot/user/service/UserSignUpService.java
moonshot-external/src/main/java/org/moonshot/discord/DiscordAppender.java

- Resolved: #279
- 회원가입 디스코드 알림 오타 수정

[Fix] #279 - 회원가입 디스코드 알림 오타 수정

---

moonshot-domain/src/main/java/org/moonshot/objective/repository/ObjectiveCustomRepositoryImpl.java

- Resolved: #284
- 소셜 API 쿼리문 수정하였습니다. 
- kr.idx, task.idx 정렬 조건 추가하였고, leftjoin으로 변경하였습니다.
- 빈 task가 들어가는 이슈는 response에는 제대로 값이 나오고 있어서 해당 PR까지 배포된 후 다시 테스트하고 동일한 이슈가 계속 있다면 바로 수정하겠습니다 ~

[Fix] #284 - 소셜 API 버그 수정

---

moonshot-api/src/main/java/org/moonshot/objective/dto/response/social/SocialKeyResultDto.java
moonshot-api/src/main/java/org/moonshot/objective/dto/response/social/SocialObjectiveDto.java

- Resolved: #288
- 소셜 탭 KR 중복 버그 수정했습니다.
- 로컬에서는 해당 버그가 재현이 안되어서 일단 배포하고 오류가 있으면 재작업하겠습니다 ....

[Fix] #288 - 소셜 KR 중복 버그 수정

---

moonshot-common/src/main/java/org/moonshot/constants/DiscordConstants.java
moonshot-external/src/main/java/org/moonshot/discord/DiscordAppender.java

- Resolved: #297 
- Discord Webhook이 Constants에 있어서 보안이슈로 연결이 끊겨서 재연결하였습니다.

[Fix] #297 - DiscordConstants 삭제 후 재연결

---

moonshot-api/src/main/java/org/moonshot/user/service/UserService.java
moonshot-external/src/main/java/org/moonshot/discord/DiscordAppender.java

- Resolved: #299 
닉네임 설정 안되는 이슈 해결

[Fix]#299 - 닉네임 설정 안되는 이슈 해결
